#
# Copyright 2022 SkyAPM org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM golang:1.14

ADD ./dubbo-go /dubbo-go
WORKDIR /dubbo-go

ENV APP_LOG_CONF_FILE /dubbo-go/test/client/conf/log.yml
ENV CONF_CONSUMER_FILE_PATH /dubbo-go/test/client/conf/client.yml

EXPOSE 8080

ENTRYPOINT ["go"]

CMD ["run", "test/client/cmd/client.go"]